# Generated by Django 4.2.27 on 2026-02-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_industry_jobtype_remove_job_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('REVIEWED', 'Reviewed'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10),
        ),
    ]
